spring.application.name=demo
# Connexion base de données
spring.datasource.url=jdbc:mysql://localhost:3306/zinbissyarr?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
jwt.secret=zinbissyarr-secret-key-tres-longue-a-changer-en-production-2026
jwt.expiration=86400000